version: "3.3"

services:

  site:
    image: docsy/docsy-example
    build:
      context: .
    #command: server --
    ports:
      - "1313:1313"
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts

